### ISSUE TITLE
Not found Europe/Kiev

### ISSUE THREAD

**Issue by freshua** [php/pecl-datetime-timezonedb#1]
I installed the latest version 2022.2, but I don`t have Europe/Kiev in the list, only the new version - Europe/Kyiv.

![image](https://user-images.githubusercontent.com/12394504/189477050-d5623eae-e5bc-47ac-a7af-84c27d4f2533.png)

**Comment by remicollet** [comment]
Try `DateTimeZone::ALL_WITH_BC` instead of default `DateTimeZone::ALL`

```
$ php -r 'var_dump(DateTimeZone::listIdentifiers(DateTimeZone::ALL_WITH_BC));'|grep Europe/K
  string(18) "Europe/Kaliningrad"
  string(11) "Europe/Kiev"
  string(12) "Europe/Kirov"
  string(11) "Europe/Kyiv"

```

**Comment by freshua** [comment]
Thanks!
