### ISSUE TITLE
Including 2022.4 ?

### ISSUE THREAD

**Issue by ilgianlu** [php/pecl-datetime-timezonedb#3]
Hi! 
IntlDateFormatter returns "Europe/Kyiv" as non existent.

new \IntlDateFormatter(
                $locale,
                \IntlDateFormatter::SHORT,
                \IntlDateFormatter::SHORT,
                "Europe/Kyiv",
                \IntlDateFormatter::GREGORIAN
 )

Does this have to do with updating timezonedb db version?

I'm using php 8.1.11 docker hub latest containerized image using debian bullseye

Thanks for any hint,
Gianluca

**Comment by derickr** [comment]
I don't know whether Intl actually uses the built-in timezonedb. It is possible that it just uses ICU, which hasn't updated its database with the new timezone yet. The [docs](https://www.php.net/manual/en/intldateformatter.create.php#refsect1-intldateformatter.create-parameters) say:

> timezone…
> This ID must be a valid identifier on ICUʼs database or an ID representing an explicit offset, such as GMT-05:30.

For now, you can still use the older `Europe/Kiev`, I presume.

I don't believe this is a problem with this timezonedb pecl package though, so I am closing this issue.

**Comment by ilgianlu** [comment]
Thanks for the advice. Sorry for the inconvenience,

Gianluca
