### ISSUE TITLE
Windows DLL

### ISSUE THREAD

**Issue by oleibman** [php/pecl-datetime-timezonedb#4]
Pecl has included a Windows dll consistently since 2014.10, but the most recent two updates (2022.5 and 2022.2) supply only tgz files suitable for Linux. Have you dropped support for Windows?

**Comment by derickr** [comment]
No, but there is currently no PECL build machine that can make windows binaries.

**Comment by oleibman** [comment]
I have a Windows machine. What would I need to install in order to make windows binaries?

**Comment by derickr** [comment]
I don't know, I'm not a Windows user.

**Comment by cmb69** [comment]
> What would I need to install in order to make windows binaries?

A lot of stuff. See https://wiki.php.net/internals/windows/stepbystepbuild_sdk_2 for the details.

I'll try to do an inofficial build ASAP, though, so you may want to wait a while.

**Comment by oleibman** [comment]
That is a lot of stuff. I will study it, but will definitely wait for the unofficial build.

**Comment by cmb69** [comment]
**Unofficial** builds: [timelib 2022.2](https://github.com/cmb69/php-ftw/actions/runs/3275013462) and [timelib 2022.5](https://github.com/cmb69/php-ftw/actions/runs/3275061560). **Use at your own risk!**

About the missing DLLs generally, see https://windows.php.net/#news-2022-10-17-1.

**Comment by oleibman** [comment]
Thank you for the information, and for the builds (which seem to work fine on my test system - your caveat is noted); and especially for responding so quickly. Closing this ticket now.
