### ISSUE TITLE
No releases available for package "pecl.php.net/timezonedb"

### ISSUE THREAD

**Issue by hughcbscrt** [php/pecl-datetime-timezonedb#8]
when i try to install timezonedb

pecl install timezonedb

> No releases available for package "pecl.php.net/timezonedb"

**Comment by derickr** [comment]
This is not a bug with the code of this extension, nor (as far as I can see) with the pecl website. I suspect your local PHP might not support the new Let's Encrypt TLS certificates that the PHP project started using.
