### ISSUE TITLE
2023d missing

### ISSUE THREAD

**Issue by Flightfreak** [php/pecl-datetime-timezonedb#9]
The latest version is 2023d (Released 2023-12-21) 
http://www.iana.org/time-zones

Is there a manual or reference on how to produce the `timezonedb.h` file?

**Comment by derickr** [comment]
I've created and released this now. I have a script: https://github.com/derickr/timelib/blob/master/zones/Makefile, but it is rather finicky.

**Comment by Flightfreak** [comment]
Thank you for the immediate response. 🥇
